version: "3.9"

services:
  haproxy:
    container_name: haproxy
    image: haproxytech/haproxy-alpine:2.4
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks: 
      - net
    volumes:
      - ./conf/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  shadowsocks-client:
    container_name: shadowsocks-client
    image: shadowsocks-client
    build:
      context: ./
      dockerfile: dockerfile
    command: ["shadowsocks2", "-c", "ss://AEAD_CHACHA20_POLY1305:${PASSWORD}@${SERVER}:${PORT}", "-socks", "0.0.0.0:1080"]
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks: 
      - net

  privoxy:
    image: vimagick/privoxy
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "1080:8118"
    volumes:
      - ./conf/privoxy/config:/etc/privoxy/config
      - ./conf/privoxy/user.action:/etc/privoxy/user.action
      - ./conf/privoxy/user.filter:/etc/privoxy/user.filter
    cap_add:
      - NET_ADMIN
    restart: always
    networks: 
      - net

networks:
  net:
    ipam:
      driver: default
