{{alias}}

direct                  = +forward-override{forward .}
proxy                   = +forward-override{forward shadowsocks-client:1080}
over_wall_proxy         = +forward-override{forward-socks5 shadowsocks-client:1080 .}
default                 = +forward-override{forward-socks5 shadowsocks-client:1080 .}

{default}
/

{direct} 
192.168.*.*
10.0.*.*
127.0.0.1
158.247.226.121
localhost
.live.com
.goproxy.cn
.mock-api.com
.humanrisk.cn
.xianganquan.com
.staticfile.org
.qiyukf.com
.youdao.com
.127.net
.qq.com
.baidu.com
.163.com
.aliyun.com
.ucloud.cn
.taobao.com
.jd.com
.cnblogs.com
.coding.net
.coding.io
.codehub.cn
.myqcloud.com
.juejin.cn
.segmentfault.com
.getpostman.com
.postman-echo.com
.postman.co
.postman.com
.ip.cn
.launchdarkly.com
.lanhuapp.com
.aliyuncs.com
.alicdn.com
.meizu.com
.bootstrap.cn
.huaweicloud.com
.grails.org
.jianshu.com
.vultr.com
.runoob.com
.hcaptcha.com
.bdstatic.com
.bdimg.com
.bcebos.com
.phpcomposer.com
.csdn.net
.csdnimg.cn
.baidustatic.com
.shimo.im
.juejin.cn
.qiniu.com
.infoq.cn
.mi.com
.flutterchina.club
.iodraw.com
.creately.com
.processon.com
.docschina.org
.bootcss.com
.xapi.com
.google-analytics.com
.createjs.cc
.51cto.com
.iconfont.cn

{proxy}

{over_wall_proxy}
.google-analytics.com
.nr-data.net
.whatismyipaddress.com
.google.com
.google.com.hk
.github.com
.githubusercontent.
.github.cnpmjs.org
.genymotion.com
.wikipedia.org
.golang.org
.youtube.com
.shadowsocks.org
.maketecheasier.com
.knowbe4.com
.hubspot.net
.proofpoint.com
.linkedin.com
.mono-project.com
